{"ast":null,"code":"\"use strict\";\n\nvar __extends = this && this.__extends || function (d, b) {\n  for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];\n  function __() {\n    this.constructor = d;\n  }\n  d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());\n};\nvar OuterSubscriber_1 = require('../OuterSubscriber');\nvar subscribeToResult_1 = require('../util/subscribeToResult');\n/**\r\n * Catches errors on the observable to be handled by returning a new observable or throwing an error.\r\n *\r\n * <img src=\"./img/catch.png\" width=\"100%\">\r\n *\r\n * @example <caption>Continues with a different Observable when there's an error</caption>\r\n *\r\n * Observable.of(1, 2, 3, 4, 5)\r\n *   .map(n => {\r\n * \t   if (n == 4) {\r\n * \t     throw 'four!';\r\n *     }\r\n *\t   return n;\r\n *   })\r\n *   .catch(err => Observable.of('I', 'II', 'III', 'IV', 'V'))\r\n *   .subscribe(x => console.log(x));\r\n *   // 1, 2, 3, I, II, III, IV, V\r\n *\r\n * @example <caption>Retries the caught source Observable again in case of error, similar to retry() operator</caption>\r\n *\r\n * Observable.of(1, 2, 3, 4, 5)\r\n *   .map(n => {\r\n * \t   if (n === 4) {\r\n * \t     throw 'four!';\r\n *     }\r\n * \t   return n;\r\n *   })\r\n *   .catch((err, caught) => caught)\r\n *   .take(30)\r\n *   .subscribe(x => console.log(x));\r\n *   // 1, 2, 3, 1, 2, 3, ...\r\n *\r\n * @example <caption>Throws a new error when the source Observable throws an error</caption>\r\n *\r\n * Observable.of(1, 2, 3, 4, 5)\r\n *   .map(n => {\r\n *     if (n == 4) {\r\n *       throw 'four!';\r\n *     }\r\n *     return n;\r\n *   })\r\n *   .catch(err => {\r\n *     throw 'error in source. Details: ' + err;\r\n *   })\r\n *   .subscribe(\r\n *     x => console.log(x),\r\n *     err => console.log(err)\r\n *   );\r\n *   // 1, 2, 3, error in source. Details: four!\r\n *\r\n * @param {function} selector a function that takes as arguments `err`, which is the error, and `caught`, which\r\n *  is the source observable, in case you'd like to \"retry\" that observable by returning it again. Whatever observable\r\n *  is returned by the `selector` will be used to continue the observable chain.\r\n * @return {Observable} An observable that originates from either the source or the observable returned by the\r\n *  catch `selector` function.\r\n * @name catchError\r\n */\nfunction catchError(selector) {\n  return function catchErrorOperatorFunction(source) {\n    var operator = new CatchOperator(selector);\n    var caught = source.lift(operator);\n    return operator.caught = caught;\n  };\n}\nexports.catchError = catchError;\nvar CatchOperator = function () {\n  function CatchOperator(selector) {\n    this.selector = selector;\n  }\n  CatchOperator.prototype.call = function (subscriber, source) {\n    return source.subscribe(new CatchSubscriber(subscriber, this.selector, this.caught));\n  };\n  return CatchOperator;\n}();\n/**\r\n * We need this JSDoc comment for affecting ESDoc.\r\n * @ignore\r\n * @extends {Ignored}\r\n */\nvar CatchSubscriber = function (_super) {\n  __extends(CatchSubscriber, _super);\n  function CatchSubscriber(destination, selector, caught) {\n    _super.call(this, destination);\n    this.selector = selector;\n    this.caught = caught;\n  }\n  // NOTE: overriding `error` instead of `_error` because we don't want\n  // to have this flag this subscriber as `isStopped`. We can mimic the\n  // behavior of the RetrySubscriber (from the `retry` operator), where\n  // we unsubscribe from our source chain, reset our Subscriber flags,\n  // then subscribe to the selector result.\n  CatchSubscriber.prototype.error = function (err) {\n    if (!this.isStopped) {\n      var result = void 0;\n      try {\n        result = this.selector(err, this.caught);\n      } catch (err2) {\n        _super.prototype.error.call(this, err2);\n        return;\n      }\n      this._unsubscribeAndRecycle();\n      this.add(subscribeToResult_1.subscribeToResult(this, result));\n    }\n  };\n  return CatchSubscriber;\n}(OuterSubscriber_1.OuterSubscriber);","map":{"version":3,"names":["__extends","d","b","p","hasOwnProperty","__","constructor","prototype","Object","create","OuterSubscriber_1","require","subscribeToResult_1","catchError","selector","catchErrorOperatorFunction","source","operator","CatchOperator","caught","lift","exports","call","subscriber","subscribe","CatchSubscriber","_super","destination","error","err","isStopped","result","err2","_unsubscribeAndRecycle","add","subscribeToResult","OuterSubscriber"],"sources":["C:/Users/HP/Desktop/4SE3/PidevSym/PiDev_Spring_Angular/Front-End/frontOffice/node_modules/ng5-slider/node_modules/rxjs/operators/catchError.js"],"sourcesContent":["\"use strict\";\r\nvar __extends = (this && this.__extends) || function (d, b) {\r\n    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];\r\n    function __() { this.constructor = d; }\r\n    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());\r\n};\r\nvar OuterSubscriber_1 = require('../OuterSubscriber');\r\nvar subscribeToResult_1 = require('../util/subscribeToResult');\r\n/**\r\n * Catches errors on the observable to be handled by returning a new observable or throwing an error.\r\n *\r\n * <img src=\"./img/catch.png\" width=\"100%\">\r\n *\r\n * @example <caption>Continues with a different Observable when there's an error</caption>\r\n *\r\n * Observable.of(1, 2, 3, 4, 5)\r\n *   .map(n => {\r\n * \t   if (n == 4) {\r\n * \t     throw 'four!';\r\n *     }\r\n *\t   return n;\r\n *   })\r\n *   .catch(err => Observable.of('I', 'II', 'III', 'IV', 'V'))\r\n *   .subscribe(x => console.log(x));\r\n *   // 1, 2, 3, I, II, III, IV, V\r\n *\r\n * @example <caption>Retries the caught source Observable again in case of error, similar to retry() operator</caption>\r\n *\r\n * Observable.of(1, 2, 3, 4, 5)\r\n *   .map(n => {\r\n * \t   if (n === 4) {\r\n * \t     throw 'four!';\r\n *     }\r\n * \t   return n;\r\n *   })\r\n *   .catch((err, caught) => caught)\r\n *   .take(30)\r\n *   .subscribe(x => console.log(x));\r\n *   // 1, 2, 3, 1, 2, 3, ...\r\n *\r\n * @example <caption>Throws a new error when the source Observable throws an error</caption>\r\n *\r\n * Observable.of(1, 2, 3, 4, 5)\r\n *   .map(n => {\r\n *     if (n == 4) {\r\n *       throw 'four!';\r\n *     }\r\n *     return n;\r\n *   })\r\n *   .catch(err => {\r\n *     throw 'error in source. Details: ' + err;\r\n *   })\r\n *   .subscribe(\r\n *     x => console.log(x),\r\n *     err => console.log(err)\r\n *   );\r\n *   // 1, 2, 3, error in source. Details: four!\r\n *\r\n * @param {function} selector a function that takes as arguments `err`, which is the error, and `caught`, which\r\n *  is the source observable, in case you'd like to \"retry\" that observable by returning it again. Whatever observable\r\n *  is returned by the `selector` will be used to continue the observable chain.\r\n * @return {Observable} An observable that originates from either the source or the observable returned by the\r\n *  catch `selector` function.\r\n * @name catchError\r\n */\r\nfunction catchError(selector) {\r\n    return function catchErrorOperatorFunction(source) {\r\n        var operator = new CatchOperator(selector);\r\n        var caught = source.lift(operator);\r\n        return (operator.caught = caught);\r\n    };\r\n}\r\nexports.catchError = catchError;\r\nvar CatchOperator = (function () {\r\n    function CatchOperator(selector) {\r\n        this.selector = selector;\r\n    }\r\n    CatchOperator.prototype.call = function (subscriber, source) {\r\n        return source.subscribe(new CatchSubscriber(subscriber, this.selector, this.caught));\r\n    };\r\n    return CatchOperator;\r\n}());\r\n/**\r\n * We need this JSDoc comment for affecting ESDoc.\r\n * @ignore\r\n * @extends {Ignored}\r\n */\r\nvar CatchSubscriber = (function (_super) {\r\n    __extends(CatchSubscriber, _super);\r\n    function CatchSubscriber(destination, selector, caught) {\r\n        _super.call(this, destination);\r\n        this.selector = selector;\r\n        this.caught = caught;\r\n    }\r\n    // NOTE: overriding `error` instead of `_error` because we don't want\r\n    // to have this flag this subscriber as `isStopped`. We can mimic the\r\n    // behavior of the RetrySubscriber (from the `retry` operator), where\r\n    // we unsubscribe from our source chain, reset our Subscriber flags,\r\n    // then subscribe to the selector result.\r\n    CatchSubscriber.prototype.error = function (err) {\r\n        if (!this.isStopped) {\r\n            var result = void 0;\r\n            try {\r\n                result = this.selector(err, this.caught);\r\n            }\r\n            catch (err2) {\r\n                _super.prototype.error.call(this, err2);\r\n                return;\r\n            }\r\n            this._unsubscribeAndRecycle();\r\n            this.add(subscribeToResult_1.subscribeToResult(this, result));\r\n        }\r\n    };\r\n    return CatchSubscriber;\r\n}(OuterSubscriber_1.OuterSubscriber));\r\n"],"mappings":"AAAA,YAAY;;AACZ,IAAIA,SAAS,GAAI,IAAI,IAAI,IAAI,CAACA,SAAS,IAAK,UAAUC,CAAC,EAAEC,CAAC,EAAE;EACxD,KAAK,IAAIC,CAAC,IAAID,CAAC,EAAE,IAAIA,CAAC,CAACE,cAAc,CAACD,CAAC,CAAC,EAAEF,CAAC,CAACE,CAAC,CAAC,GAAGD,CAAC,CAACC,CAAC,CAAC;EACrD,SAASE,EAAE,GAAG;IAAE,IAAI,CAACC,WAAW,GAAGL,CAAC;EAAE;EACtCA,CAAC,CAACM,SAAS,GAAGL,CAAC,KAAK,IAAI,GAAGM,MAAM,CAACC,MAAM,CAACP,CAAC,CAAC,IAAIG,EAAE,CAACE,SAAS,GAAGL,CAAC,CAACK,SAAS,EAAE,IAAIF,EAAE,EAAE,CAAC;AACxF,CAAC;AACD,IAAIK,iBAAiB,GAAGC,OAAO,CAAC,oBAAoB,CAAC;AACrD,IAAIC,mBAAmB,GAAGD,OAAO,CAAC,2BAA2B,CAAC;AAC9D;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA,SAASE,UAAU,CAACC,QAAQ,EAAE;EAC1B,OAAO,SAASC,0BAA0B,CAACC,MAAM,EAAE;IAC/C,IAAIC,QAAQ,GAAG,IAAIC,aAAa,CAACJ,QAAQ,CAAC;IAC1C,IAAIK,MAAM,GAAGH,MAAM,CAACI,IAAI,CAACH,QAAQ,CAAC;IAClC,OAAQA,QAAQ,CAACE,MAAM,GAAGA,MAAM;EACpC,CAAC;AACL;AACAE,OAAO,CAACR,UAAU,GAAGA,UAAU;AAC/B,IAAIK,aAAa,GAAI,YAAY;EAC7B,SAASA,aAAa,CAACJ,QAAQ,EAAE;IAC7B,IAAI,CAACA,QAAQ,GAAGA,QAAQ;EAC5B;EACAI,aAAa,CAACX,SAAS,CAACe,IAAI,GAAG,UAAUC,UAAU,EAAEP,MAAM,EAAE;IACzD,OAAOA,MAAM,CAACQ,SAAS,CAAC,IAAIC,eAAe,CAACF,UAAU,EAAE,IAAI,CAACT,QAAQ,EAAE,IAAI,CAACK,MAAM,CAAC,CAAC;EACxF,CAAC;EACD,OAAOD,aAAa;AACxB,CAAC,EAAG;AACJ;AACA;AACA;AACA;AACA;AACA,IAAIO,eAAe,GAAI,UAAUC,MAAM,EAAE;EACrC1B,SAAS,CAACyB,eAAe,EAAEC,MAAM,CAAC;EAClC,SAASD,eAAe,CAACE,WAAW,EAAEb,QAAQ,EAAEK,MAAM,EAAE;IACpDO,MAAM,CAACJ,IAAI,CAAC,IAAI,EAAEK,WAAW,CAAC;IAC9B,IAAI,CAACb,QAAQ,GAAGA,QAAQ;IACxB,IAAI,CAACK,MAAM,GAAGA,MAAM;EACxB;EACA;EACA;EACA;EACA;EACA;EACAM,eAAe,CAAClB,SAAS,CAACqB,KAAK,GAAG,UAAUC,GAAG,EAAE;IAC7C,IAAI,CAAC,IAAI,CAACC,SAAS,EAAE;MACjB,IAAIC,MAAM,GAAG,KAAK,CAAC;MACnB,IAAI;QACAA,MAAM,GAAG,IAAI,CAACjB,QAAQ,CAACe,GAAG,EAAE,IAAI,CAACV,MAAM,CAAC;MAC5C,CAAC,CACD,OAAOa,IAAI,EAAE;QACTN,MAAM,CAACnB,SAAS,CAACqB,KAAK,CAACN,IAAI,CAAC,IAAI,EAAEU,IAAI,CAAC;QACvC;MACJ;MACA,IAAI,CAACC,sBAAsB,EAAE;MAC7B,IAAI,CAACC,GAAG,CAACtB,mBAAmB,CAACuB,iBAAiB,CAAC,IAAI,EAAEJ,MAAM,CAAC,CAAC;IACjE;EACJ,CAAC;EACD,OAAON,eAAe;AAC1B,CAAC,CAACf,iBAAiB,CAAC0B,eAAe,CAAE"},"metadata":{},"sourceType":"script","externalDependencies":[]}